
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    driver.get("https://ramandy007.github.io/leave_management/faculty/");
    driver.manage().window().setSize(new Dimension(1366, 728));
    driver.findElement(By.id("un")).click();
    driver.findElement(By.id("un")).click();
    driver.findElement(By.id("un")).sendKeys("cb.en.u4cse17213");
    driver.findElement(By.cssSelector(".btn-info")).click();
    assertThat(driver.switchTo().alert().getText(), is("Empty Password"));
    driver.findElement(By.id("pw")).click();
    driver.findElement(By.id("pw")).sendKeys("a");
    driver.findElement(By.cssSelector(".btn-info")).click();
    assertThat(driver.switchTo().alert().getText(), is("Invalid Credentials"));
    driver.findElement(By.id("pw")).click();
    driver.findElement(By.id("pw")).sendKeys("balaji2k.");
    driver.findElement(By.id("pw")).sendKeys(Keys.ENTER);
    driver.close();
  }
}
